sudo: required
language: cpp
services:
  - docker 
before_install:
  - docker pull lasote/conangcc63
  - docker run lasote/conangcc63
  - docker ps -a
install:
  # Download conan
  - sudo pip install --upgrade conan
  # Automatic detection of your arch, compiler, etc
  - conan user
  
script:
  # Install dependencies, build, test and create package
  - conan test_package
