version: 1.0.{build}
platform:
  - x64

install:
  - cmd: echo "Downloading conan..."
  - ps: wget https://s3-eu-west-1.amazonaws.com/conanio/downloads/conan-win_0_3_0.exe -OutFile conan_installer.exe
  - cmd: conan_installer.exe /VERYSILENT
  - cmd: set PATH=%PATH%;C:\Program Files (x86)\Conan\conan
  - cmd: conan --version

build_script:
  - cmd: mkdir build 
  - cmd: mkdir build/bin
  - cmd: conan install -o gtest:shared=True
  - cmd: cd build 
  - cmd: cmake ../ -DBUILD_TEST=TRUE  -G "Visual Studio 14 2015 Win64"
  - cmd: cmake --build . --config Release

test_script:
  - cmd: ./bin/encryption_test.exe
