build: false
platform: x86
environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan # Install Conan.io
  - conan user # It creates the conan data directory

test_script:
  - conan create conan/testing --build missing
